"""init

Revision ID: c53f55e9231e
Revises: 
Create Date: 2021-09-24 20:18:54.466121

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'c53f55e9231e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('npm', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('npm')
    )
    op.create_table('courses',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('matkul', sa.String(length=25), nullable=False),
    sa.Column('teacher', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher'], ['users.npm'], name='fk_courses_users_npm_teacher'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses_users',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('course', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['courses.id'], name='fk_courses_users_courses_course_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.npm'], name='fk_courses_users_users_user_npm', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses_users')
    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###
