"""Add notes and hidden

Revision ID: c76513259483
Revises: a9e1956cba63
Create Date: 2021-10-04 07:36:35.199131

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "c76513259483"
down_revision = "a9e1956cba63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses", sa.Column("notes_short", sa.String(length=100), nullable=True)
    )
    op.add_column("courses", sa.Column("hidden", sa.Boolean(), nullable=True))
    op.execute("UPDATE courses SET hidden = false")
    op.alter_column("courses", "hidden", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "hidden")
    op.drop_column("courses", "notes_short")
    # ### end Alembic commands ###
